// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmacyIMS.Data;

#nullable disable

namespace PharmacyIMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PharmacyIMS.Models.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovalNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DosageForm")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GenericName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MedicineCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PrescriptionType")
                        .HasColumnType("int");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Specification")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StockAlertLevel")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Medicines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApprovalNo = "国药准字Z44022100",
                            CategoryId = 1,
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DosageForm = "颗粒剂",
                            ExpiryDate = new DateTime(2027, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "复方感冒灵颗粒",
                            Manufacturer = "华润三九医药",
                            MedicineCode = "YP-001",
                            MedicineName = "感冒灵颗粒",
                            PrescriptionType = 1,
                            PurchasePrice = 8.50m,
                            SalePrice = 15.00m,
                            Specification = "10g*9袋",
                            StockAlertLevel = 20,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 2,
                            ApprovalNo = "国药准字H10900089",
                            CategoryId = 1,
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DosageForm = "胶囊剂",
                            ExpiryDate = new DateTime(2027, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "布洛芬",
                            Manufacturer = "中美史克制药",
                            MedicineCode = "YP-002",
                            MedicineName = "布洛芬缓释胶囊",
                            PrescriptionType = 1,
                            PurchasePrice = 6.20m,
                            SalePrice = 12.50m,
                            Specification = "0.3g*24粒",
                            StockAlertLevel = 15,
                            StockQuantity = 85
                        },
                        new
                        {
                            Id = 3,
                            ApprovalNo = "国药准字H13020726",
                            CategoryId = 1,
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DosageForm = "胶囊剂",
                            ExpiryDate = new DateTime(2027, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "阿莫西林",
                            Manufacturer = "华北制药集团",
                            MedicineCode = "YP-003",
                            MedicineName = "阿莫西林胶囊",
                            PrescriptionType = 0,
                            PurchasePrice = 3.80m,
                            SalePrice = 8.00m,
                            Specification = "0.25g*24粒",
                            StockAlertLevel = 30,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 4,
                            ApprovalNo = "国药准字J20180025",
                            CategoryId = 2,
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DosageForm = "片剂",
                            ExpiryDate = new DateTime(2027, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "硝苯地平",
                            Manufacturer = "拜耳医药保健",
                            MedicineCode = "YP-004",
                            MedicineName = "硝苯地平控释片",
                            PrescriptionType = 0,
                            PurchasePrice = 18.50m,
                            SalePrice = 35.00m,
                            Specification = "30mg*7片",
                            StockAlertLevel = 10,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 5,
                            ApprovalNo = "国药准字J20171021",
                            CategoryId = 2,
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DosageForm = "片剂",
                            ExpiryDate = new DateTime(2027, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "阿司匹林",
                            Manufacturer = "拜耳医药保健",
                            MedicineCode = "YP-005",
                            MedicineName = "阿司匹林肠溶片",
                            PrescriptionType = 0,
                            PurchasePrice = 5.00m,
                            SalePrice = 10.00m,
                            Specification = "100mg*30片",
                            StockAlertLevel = 25,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 6,
                            ApprovalNo = "国药准字H20030413",
                            CategoryId = 3,
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DosageForm = "胶囊剂",
                            ExpiryDate = new DateTime(2027, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "奥美拉唑",
                            Manufacturer = "阿斯利康制药",
                            MedicineCode = "YP-006",
                            MedicineName = "奥美拉唑肠溶胶囊",
                            PrescriptionType = 0,
                            PurchasePrice = 12.00m,
                            SalePrice = 25.00m,
                            Specification = "20mg*14粒",
                            StockAlertLevel = 10,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 7,
                            ApprovalNo = "国药准字H20000690",
                            CategoryId = 3,
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DosageForm = "散剂",
                            ExpiryDate = new DateTime(2027, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "蒙脱石",
                            Manufacturer = "博福-益普生制药",
                            MedicineCode = "YP-007",
                            MedicineName = "蒙脱石散",
                            PrescriptionType = 1,
                            PurchasePrice = 7.50m,
                            SalePrice = 16.00m,
                            Specification = "3g*10袋",
                            StockAlertLevel = 15,
                            StockQuantity = 95
                        },
                        new
                        {
                            Id = 8,
                            ApprovalNo = "国药准字Z53021104",
                            CategoryId = 4,
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DosageForm = "气雾剂",
                            ExpiryDate = new DateTime(2027, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "云南白药",
                            Manufacturer = "云南白药集团",
                            MedicineCode = "YP-008",
                            MedicineName = "云南白药气雾剂",
                            PrescriptionType = 1,
                            PurchasePrice = 22.00m,
                            SalePrice = 45.00m,
                            Specification = "85g+30g",
                            StockAlertLevel = 8,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 9,
                            ApprovalNo = "国药准字Z44023754",
                            CategoryId = 4,
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DosageForm = "搽剂",
                            ExpiryDate = new DateTime(2027, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "红花油",
                            Manufacturer = "广东泰恩康制药",
                            MedicineCode = "YP-009",
                            MedicineName = "红花油",
                            PrescriptionType = 1,
                            PurchasePrice = 4.50m,
                            SalePrice = 9.80m,
                            Specification = "20ml",
                            StockAlertLevel = 12,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 10,
                            ApprovalNo = "皖20160052",
                            CategoryId = 5,
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DosageForm = "饮片",
                            ExpiryDate = new DateTime(2026, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "枸杞子",
                            Manufacturer = "亳州中药材市场",
                            MedicineCode = "YP-010",
                            MedicineName = "枸杞子",
                            PrescriptionType = 2,
                            PurchasePrice = 25.00m,
                            SalePrice = 48.00m,
                            Specification = "500g/袋",
                            StockAlertLevel = 8,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 11,
                            ApprovalNo = "国药准字H31022339",
                            CategoryId = 6,
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DosageForm = "片剂",
                            ExpiryDate = new DateTime(2027, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "复合维生素B",
                            Manufacturer = "上海信谊药厂",
                            MedicineCode = "YP-011",
                            MedicineName = "复合维生素B片",
                            PrescriptionType = 1,
                            PurchasePrice = 3.20m,
                            SalePrice = 7.00m,
                            Specification = "100片",
                            StockAlertLevel = 30,
                            StockQuantity = 180
                        },
                        new
                        {
                            Id = 12,
                            ApprovalNo = "国药准字H10950029",
                            CategoryId = 6,
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DosageForm = "片剂",
                            ExpiryDate = new DateTime(2027, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "碳酸钙D3",
                            Manufacturer = "惠氏制药",
                            MedicineCode = "YP-012",
                            MedicineName = "钙尔奇D片",
                            PrescriptionType = 1,
                            PurchasePrice = 28.00m,
                            SalePrice = 58.00m,
                            Specification = "60片",
                            StockAlertLevel = 10,
                            StockQuantity = 55
                        });
                });

            modelBuilder.Entity("PharmacyIMS.Models.MedicineBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("MedicineBatches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatchNo = "B20260701001",
                            CreateTime = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(2027, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicineId = 1,
                            ProductionDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchaseOrderId = 1,
                            Quantity = 100,
                            UnitPrice = 8.50m
                        },
                        new
                        {
                            Id = 2,
                            BatchNo = "B20260701002",
                            CreateTime = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(2027, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicineId = 2,
                            ProductionDate = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchaseOrderId = 1,
                            Quantity = 50,
                            UnitPrice = 6.20m
                        },
                        new
                        {
                            Id = 3,
                            BatchNo = "B20260701003",
                            CreateTime = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(2027, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicineId = 3,
                            ProductionDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchaseOrderId = 1,
                            Quantity = 80,
                            UnitPrice = 3.80m
                        },
                        new
                        {
                            Id = 4,
                            BatchNo = "B20260705001",
                            CreateTime = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(2027, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicineId = 4,
                            ProductionDate = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchaseOrderId = 2,
                            Quantity = 40,
                            UnitPrice = 18.50m
                        });
                });

            modelBuilder.Entity("PharmacyIMS.Models.MedicineCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("MedicineCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "感冒用药",
                            Description = "治疗感冒、发烧、咳嗽等常见症状"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "心脑血管",
                            Description = "高血压、心脏病等心脑血管相关药品"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "消化系统",
                            Description = "胃肠用药、肝病用药等"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "外用药品",
                            Description = "膏药、软膏、消毒液等外用制剂"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "中药饮片",
                            Description = "中药材、中药配方颗粒等"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "维生素类",
                            Description = "维生素、矿物质及营养补充剂"
                        });
                });

            modelBuilder.Entity("PharmacyIMS.Models.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateTime = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OperatorName = "admin",
                            OrderNo = "CG20260701001",
                            PurchaseDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "常规采购",
                            Status = 1,
                            SupplierId = 1,
                            TotalAmount = 1850.00m
                        },
                        new
                        {
                            Id = 2,
                            CreateTime = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OperatorName = "admin",
                            OrderNo = "CG20260705001",
                            PurchaseDate = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "补货采购",
                            Status = 1,
                            SupplierId = 2,
                            TotalAmount = 1200.00m
                        });
                });

            modelBuilder.Entity("PharmacyIMS.Models.PurchaseOrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpiryDate = new DateTime(2027, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicineId = 1,
                            PurchaseOrderId = 1,
                            Quantity = 100,
                            SubTotal = 850.00m,
                            UnitPrice = 8.50m
                        },
                        new
                        {
                            Id = 2,
                            ExpiryDate = new DateTime(2027, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicineId = 2,
                            PurchaseOrderId = 1,
                            Quantity = 50,
                            SubTotal = 310.00m,
                            UnitPrice = 6.20m
                        },
                        new
                        {
                            Id = 3,
                            ExpiryDate = new DateTime(2027, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicineId = 3,
                            PurchaseOrderId = 1,
                            Quantity = 80,
                            SubTotal = 304.00m,
                            UnitPrice = 3.80m
                        },
                        new
                        {
                            Id = 4,
                            ExpiryDate = new DateTime(2027, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicineId = 5,
                            PurchaseOrderId = 1,
                            Quantity = 60,
                            SubTotal = 300.00m,
                            UnitPrice = 5.00m
                        },
                        new
                        {
                            Id = 5,
                            ExpiryDate = new DateTime(2027, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicineId = 11,
                            PurchaseOrderId = 1,
                            Quantity = 100,
                            SubTotal = 320.00m,
                            UnitPrice = 3.20m
                        },
                        new
                        {
                            Id = 6,
                            ExpiryDate = new DateTime(2027, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicineId = 4,
                            PurchaseOrderId = 2,
                            Quantity = 40,
                            SubTotal = 740.00m,
                            UnitPrice = 18.50m
                        },
                        new
                        {
                            Id = 7,
                            ExpiryDate = new DateTime(2027, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicineId = 6,
                            PurchaseOrderId = 2,
                            Quantity = 30,
                            SubTotal = 360.00m,
                            UnitPrice = 12.00m
                        },
                        new
                        {
                            Id = 8,
                            ExpiryDate = new DateTime(2027, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicineId = 8,
                            PurchaseOrderId = 2,
                            Quantity = 20,
                            SubTotal = 440.00m,
                            UnitPrice = 22.00m
                        });
                });

            modelBuilder.Entity("PharmacyIMS.Models.PurchaseReturnOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("PurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseReturnOrders");
                });

            modelBuilder.Entity("PharmacyIMS.Models.PurchaseReturnOrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseReturnOrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PurchaseReturnOrderId");

                    b.ToTable("PurchaseReturnOrderDetails");
                });

            modelBuilder.Entity("PharmacyIMS.Models.SaleOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.ToTable("SaleOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateTime = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "张三",
                            CustomerPhone = "13900001111",
                            OperatorName = "admin",
                            OrderNo = "XS20260702001",
                            Remark = "零售",
                            SaleDate = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TotalAmount = 43.00m
                        },
                        new
                        {
                            Id = 2,
                            CreateTime = new DateTime(2026, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "李四",
                            CustomerPhone = "13900002222",
                            OperatorName = "admin",
                            OrderNo = "XS20260706001",
                            Remark = "零售",
                            SaleDate = new DateTime(2026, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TotalAmount = 128.00m
                        });
                });

            modelBuilder.Entity("PharmacyIMS.Models.SaleOrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SaleOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("SaleOrderId");

                    b.ToTable("SaleOrderDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MedicineId = 1,
                            Quantity = 2,
                            SaleOrderId = 1,
                            SubTotal = 30.00m,
                            UnitPrice = 15.00m
                        },
                        new
                        {
                            Id = 2,
                            MedicineId = 2,
                            Quantity = 1,
                            SaleOrderId = 1,
                            SubTotal = 12.50m,
                            UnitPrice = 12.50m
                        },
                        new
                        {
                            Id = 3,
                            MedicineId = 4,
                            Quantity = 2,
                            SaleOrderId = 2,
                            SubTotal = 70.00m,
                            UnitPrice = 35.00m
                        },
                        new
                        {
                            Id = 4,
                            MedicineId = 6,
                            Quantity = 1,
                            SaleOrderId = 2,
                            SubTotal = 25.00m,
                            UnitPrice = 25.00m
                        },
                        new
                        {
                            Id = 5,
                            MedicineId = 9,
                            Quantity = 3,
                            SaleOrderId = 2,
                            SubTotal = 29.40m,
                            UnitPrice = 9.80m
                        });
                });

            modelBuilder.Entity("PharmacyIMS.Models.SaleReturnOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SaleOrderId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("SaleOrderId");

                    b.ToTable("SaleReturnOrders");
                });

            modelBuilder.Entity("PharmacyIMS.Models.SaleReturnOrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SaleReturnOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("SaleReturnOrderId");

                    b.ToTable("SaleReturnOrderDetails");
                });

            modelBuilder.Entity("PharmacyIMS.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "北京市东城区xx路1号",
                            ContactPerson = "王经理",
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LicenseNo = "京AA0100001",
                            Phone = "13800001111",
                            SupplierName = "国药控股股份有限公司"
                        },
                        new
                        {
                            Id = 2,
                            Address = "上海市浦东新区xx路2号",
                            ContactPerson = "李经理",
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LicenseNo = "沪AB0200002",
                            Phone = "13800002222",
                            SupplierName = "华润医药商业集团"
                        },
                        new
                        {
                            Id = 3,
                            Address = "武汉市汉阳区xx路3号",
                            ContactPerson = "张经理",
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LicenseNo = "鄂AC0300003",
                            Phone = "13800003333",
                            SupplierName = "九州通医药集团"
                        },
                        new
                        {
                            Id = 4,
                            Address = "广州市荔湾区xx路4号",
                            ContactPerson = "陈经理",
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LicenseNo = "粤AD0400004",
                            Phone = "13800004444",
                            SupplierName = "广州医药有限公司"
                        });
                });

            modelBuilder.Entity("PharmacyIMS.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "13800000000",
                            RealName = "系统管理员",
                            Role = 0,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("PharmacyIMS.Models.Medicine", b =>
                {
                    b.HasOne("PharmacyIMS.Models.MedicineCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PharmacyIMS.Models.MedicineBatch", b =>
                {
                    b.HasOne("PharmacyIMS.Models.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyIMS.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId");

                    b.Navigation("Medicine");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("PharmacyIMS.Models.PurchaseOrder", b =>
                {
                    b.HasOne("PharmacyIMS.Models.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("PharmacyIMS.Models.PurchaseOrderDetail", b =>
                {
                    b.HasOne("PharmacyIMS.Models.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyIMS.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Details")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("PharmacyIMS.Models.PurchaseReturnOrder", b =>
                {
                    b.HasOne("PharmacyIMS.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId");

                    b.HasOne("PharmacyIMS.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("PharmacyIMS.Models.PurchaseReturnOrderDetail", b =>
                {
                    b.HasOne("PharmacyIMS.Models.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyIMS.Models.PurchaseReturnOrder", "PurchaseReturnOrder")
                        .WithMany("Details")
                        .HasForeignKey("PurchaseReturnOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("PurchaseReturnOrder");
                });

            modelBuilder.Entity("PharmacyIMS.Models.SaleOrderDetail", b =>
                {
                    b.HasOne("PharmacyIMS.Models.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyIMS.Models.SaleOrder", "SaleOrder")
                        .WithMany("Details")
                        .HasForeignKey("SaleOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("SaleOrder");
                });

            modelBuilder.Entity("PharmacyIMS.Models.SaleReturnOrder", b =>
                {
                    b.HasOne("PharmacyIMS.Models.SaleOrder", "SaleOrder")
                        .WithMany()
                        .HasForeignKey("SaleOrderId");

                    b.Navigation("SaleOrder");
                });

            modelBuilder.Entity("PharmacyIMS.Models.SaleReturnOrderDetail", b =>
                {
                    b.HasOne("PharmacyIMS.Models.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyIMS.Models.SaleReturnOrder", "SaleReturnOrder")
                        .WithMany("Details")
                        .HasForeignKey("SaleReturnOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("SaleReturnOrder");
                });

            modelBuilder.Entity("PharmacyIMS.Models.PurchaseOrder", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("PharmacyIMS.Models.PurchaseReturnOrder", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("PharmacyIMS.Models.SaleOrder", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("PharmacyIMS.Models.SaleReturnOrder", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("PharmacyIMS.Models.Supplier", b =>
                {
                    b.Navigation("PurchaseOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
